tap "anomalyco/tap"
tap "charmbracelet/tap"
tap "llmmanorg/tap"
tap "ublue-os/tap", trusted: true
tap "ublue-os/experimental-tap", trusted: true
brew "anomalyco/tap/opencode-v2"
brew "block-goose-cli"
brew "charmbracelet/tap/crush"
brew "kimi-code"
brew "llm"
brew "llmfit"
brew "llmmanorg/tap/llmman"
brew "mistral-vibe"
brew "qwen-code"
brew "ublue-os/tap/linux-mcp-server"
cask "claude-code"
cask "codex"
cask "copilot-cli"
cask "ublue-os/tap/antigravity-cli-linux"
cask "ublue-os/tap/antigravity-linux"
cask "ublue-os/experimental-tap/opencode-desktop-linux"
cask "ublue-os/tap/goose-linux"
cask "ublue-os/tap/lm-studio-linux"
flatpak "ai.jan.Jan"
