tap "ublue-os/experimental-tap", trusted: true
tap "ublue-os/tap", trusted: true
cask "ublue-os/experimental-tap/cursor-linux"
cask "ublue-os/experimental-tap/clion-linux"
cask "ublue-os/experimental-tap/datagrip-linux"
cask "ublue-os/experimental-tap/dataspell-linux"
cask "ublue-os/experimental-tap/emacs-app-linux"
cask "ublue-os/experimental-tap/goland-linux"
cask "ublue-os/experimental-tap/intellij-idea-linux"
cask "ublue-os/experimental-tap/phpstorm-linux"
cask "ublue-os/experimental-tap/pycharm-linux"
cask "ublue-os/experimental-tap/rider-linux"
cask "ublue-os/experimental-tap/rubymine-linux"
cask "ublue-os/experimental-tap/rustrover-linux"
cask "ublue-os/experimental-tap/webstorm-linux"
cask "ublue-os/tap/zed-linux"
