# full-desktop.Brewfile
# Comprehensive collection of GNOME Circle and community flatpak applications
#
# This Brewfile contains a curated list of high-quality flatpak applications
# that provide a full desktop experience on Bluefin. Install with:
#   brew bundle --file=/usr/share/ublue-os/homebrew/full-desktop.Brewfile
#
# These applications are all available from Flathub and include GNOME Circle
# apps and other well-maintained community applications.

flatpak "app.drey.Biblioteca"
flatpak "app.drey.Damask"
flatpak "app.drey.Dialect"
flatpak "app.drey.EarTag"
flatpak "app.drey.Elastic"
flatpak "app.fotema.Fotema"
flatpak "com.belmoussaoui.Authenticator"
flatpak "com.belmoussaoui.Decoder"
flatpak "com.clarahobbs.chessclock"
flatpak "com.github.finefindus.eyedropper"
flatpak "com.github.flxzt.rnote"
flatpak "com.github.hugolabe.Wike"
flatpak "com.github.huluti.Curtail"
flatpak "com.github.johnfactotum.Foliate"
flatpak "com.github.maoschanz.drawing"
flatpak "com.github.neithern.g4music"
flatpak "com.github.rajsolai.textsnatcher"
flatpak "com.rafaelmardojai.Blanket"
flatpak "de.haeckerfelix.AudioSharing"
flatpak "de.haeckerfelix.Fragments"
flatpak "dev.bragefuglseth.Fretboard"
flatpak "dev.geopjr.Calligraphy"
flatpak "dev.geopjr.Collision"
flatpak "dev.geopjr.Tuba"
flatpak "hu.kramo.Cartridges"
flatpak "im.dino.Dino"
flatpak "info.febvre.Komikku"
flatpak "io.github.diegoivan.pdf_metadata_editor"
flatpak "io.github.lainsce.Khronos"
flatpak "io.github.mrvladus.List"
flatpak "io.github.seadve.Mousai"
flatpak "io.gitlab.adhami3310.Converter"
flatpak "io.gitlab.news_flash.NewsFlash"
flatpak "io.gitlab.zehkira.Monophony"
flatpak "it.mijorus.smile"
flatpak "org.freedesktop.Bustle"
flatpak "org.freedesktop.Piper"
flatpak "org.gaphor.Gaphor"
flatpak "org.gnome.design.Emblem"
flatpak "org.gnome.design.IconLibrary"
flatpak "org.gnome.gitlab.cheywood.Buffer"
flatpak "org.gnome.gitlab.cheywood.Pulp"
flatpak "com.frac_tion.teleport"
flatpak "com.ranfdev.Notify"
flatpak "org.gnome.gitlab.somas.Apostrophe"
flatpak "org.gnome.gitlab.YaLTeR.Identity"
flatpak "dev.Cogitri.Health"
flatpak "org.gnome.Podcasts"
flatpak "org.gnome.Solanum"
flatpak "org.gnome.World.Citations"
flatpak "org.gnome.World.Iotas"
flatpak "org.gnome.World.PikaBackup"
flatpak "org.nickvision.cavalier"
flatpak "org.nickvision.tubeconverter"
flatpak "re.sonny.Commit"
flatpak "re.sonny.Eloquent"
flatpak "re.sonny.Tangram"
flatpak "uk.co.ibboard.cawbird"
