tap "ublue-os/tap", trusted: true
cask "ublue-os/tap/visual-studio-code-linux"
cask "ublue-os/tap/visual-studio-code-linux@insiders"
cask "ublue-os/tap/vscodium-linux"
cask "ublue-os/tap/antigravity-linux"
cask "ublue-os/tap/jetbrains-toolbox-linux"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-azuretools.vscode-containers"
brew "nvim"
brew "micro"
brew "helix"
brew "devcontainer"
