#!/usr/bin/bash
# Regenerate gpu-detect/src/nvidia_open_ids.rs from NVIDIA's open-gpu-kernel-modules README.
# The README's "Compatible GPUs" table is NVIDIA's own list of devices the open kernel modules
# support (Turing and newer), so it is the source of truth for "can use the open driver".
#
# Usage: installer/gen-nvidia-ids.sh <open-gpu-kernel-modules tag, e.g. 615.71.09>
set -euo pipefail

tag="${1:?usage: gen-nvidia-ids.sh <open-gpu-kernel-modules tag>}"
out="$(dirname "${BASH_SOURCE[0]}")/gpu-detect/src/nvidia_open_ids.rs"
url="https://raw.githubusercontent.com/NVIDIA/open-gpu-kernel-modules/${tag}/README.md"

readme="$(curl --retry 3 --fail --silent --show-error --location "${url}")"

# Table rows look like "| NVIDIA TITAN RTX | 1E02 |" or "| Quadro RTX 8000 | 1E30 1028 129E |".
# The first token of the last column is the PCI device ID; the other two are subsystem IDs.
ids="$(awk -F'|' '
    /^## Compatible GPUs/ { in_section = 1; next }
    in_section && /^## / { exit }
    in_section && NF >= 3 {
        split($3, f, " ")
        if (f[1] ~ /^[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]$/) print toupper(f[1])
    }
' <<<"${readme}" | sort -u)"

count="$(wc -l <<<"${ids}")"
if [[ "${count}" -lt 200 ]]; then
    echo "error: only ${count} device IDs parsed from ${url}; the README layout probably changed" >&2
    exit 1
fi

{
    echo "// Generated by installer/gen-nvidia-ids.sh from NVIDIA/open-gpu-kernel-modules ${tag}. Do not edit."
    echo "// PCI device IDs (vendor 0x10de) the NVIDIA open kernel modules support: Turing and newer."
    echo "// Sorted and unique, so lookups can binary search."
    echo "pub const NVIDIA_OPEN_TAG: &str = \"${tag}\";"
    echo
    echo "pub const NVIDIA_OPEN_DEVICE_IDS: &[u16] = &["
    while read -r id; do echo "    0x${id},"; done <<<"${ids}"
    echo "];"
} > "${out}"

echo "wrote ${count} device IDs to ${out}"
